-- Enable Supabase Realtime on the `posts` table so the dashboard
-- can subscribe to INSERT/UPDATE/DELETE events and refresh automatically
-- when new posts are generated by the webhook pipeline.

ALTER PUBLICATION supabase_realtime ADD TABLE public.posts;
